# Generated by Django 4.2.6 on 2023-10-25 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='instuctor',
            new_name='instructor',
        ),
    ]
